from yarginator.core.chart import Chart
from yarginator.core.timing import TempoMap
from yarginator.feedback import ReviewItem
from yarginator.reaper import project as rproject
from yarginator.reaper.rpp import dumps, parse, tokenize

TEMPLATE = """<REAPER_PROJECT 0.1 "7.27/win64" 1700000000
  RIPPLE 0
  TEMPO 120 4 4
  MARKER 1 3.5 "Mine" 0
  <TRACK {AAAAAAAA-0000-0000-0000-000000000000}
    NAME "PART DRUMS"
    VOLPAN 1 0 -1 -1 1
    <ITEM
      POSITION 0
      LENGTH 10
    >
    <FXCHAIN
      <VST "VST: ReaEQ (Cockos)" reaeq.dll 0 "" 1919247729<56535472656571726561657100000000> ""
        cWVyde5e7f4CAAAAAQAAAAAAAAACAAAAAAAAAAIAAAABAAAAAAAAAAIAAAAAAAAAOAAAAAEAAAAAABAA
      >
    >
  >
>
"""


OLD_SONG_TEMPLATE = """<REAPER_PROJECT 0.1 "7.27/win64" 0
  TEMPO 180 4 4
  <TRACK {A}
    NAME "Old Band - Old Song"
    <ITEM
      POSITION 0
      LENGTH 212
      FADEIN 1 0.01 0 1 0 0 0
      IGUID {I1}
      NAME "Old Song.mp3"
      <SOURCE MP3
        FILE "D:\\old\\Old Song.mp3"
      >
    >
  >
  <TRACK {B}
    NAME Guitar
    <ITEM
      POSITION 0
      LENGTH 212
      <SOURCE MP3
        FILE "D:\\old\\Guitar.mp3"
      >
    >
  >
  <TRACK {C}
    NAME Drums
  >
  <TRACK {D}
    NAME "PART GUITAR"
    <ITEM
      POSITION 0
      LENGTH 212
      IGUID {I2}
      <SOURCE MIDI
        HASDATA 1 480 QN
        CCINTERP 32
        POOLEDEVTS {P}
        E 3840 90 61 60
        E 60 80 61 00
        <X 0 0 0 0 1 "OLD TEXT"
          /wFPTEQgVEVYVA==
        >
        E 0 b0 7b 00
        GUID {G}
        CFGEDIT 1 1 0 1 0 1 1 1 1 1 1 0.125 422
      >
    >
  >
  <TRACK {E}
    NAME "PART DRUMS"
    MIDICOLORMAPFN "D:\\missing\\rockband_drums.png"
    <ITEM
      POSITION 0
      LENGTH 212
      <SOURCE MIDI
        HASDATA 1 480 QN
        E 0 90 60 6c
        E 60 80 60 00
        CFGEDIT 9 9 9
      >
    >
  >
>
"""


def test_template_from_an_old_song(tmp_path):
    tpl = tmp_path / "t.RPP"
    tpl.write_text(OLD_SONG_TEMPLATE)
    cmaps = tmp_path / "maps"
    cmaps.mkdir()
    for f in ("rockband_drums.png", "rockband_guitarbass.png", "rockband_vox-other.png"):
        (cmaps / f).write_bytes(b"")
    stems = {}
    for k in ("drums", "keys", "song"):
        stems[k] = tmp_path / f"{k}.wav"
        stems[k].write_bytes(b"")
    chart = Chart(TempoMap.constant(123))
    chart.track("PART VOCALS").add_lyric(960, "do").add_note(960, 240, 60)
    root = rproject.build(chart, stems, [], tpl, color_maps=cmaps, song_title="New Band - New Song")
    text = dumps(root)
    assert "Old Song" not in text and "Guitar.mp3" not in text and "OLD TEXT" not in text and "POOLEDEVTS" not in text

    tracks = {t.value("NAME")[0]: t for t in root.nodes("TRACK")}
    names = list(tracks)
    # full mix took the first (song-named) track; new keys audio sits with the audio tracks
    assert names[:4] == ["New Band - New Song", "Guitar", "Drums", "keys"]
    assert tracks["New Band - New Song"].find("ITEM").line("FADEIN") is not None  # template item settings kept
    assert not list(tracks["Guitar"].nodes("ITEM"))                                # no stem -> emptied
    # unused template chart track: emptied but keeps its editor settings
    pg = tracks["PART GUITAR"].find("ITEM").find("SOURCE")
    assert [c.raw for c in pg.children if getattr(c, "key", "") == "E"] == ["E 0 b0 7b 00"]
    assert pg.line("CFGEDIT") is not None
    # new chart track copies MIDI editor settings from PART DRUMS; colour maps point at the local folder
    assert tracks["PART VOCALS"].find("ITEM").find("SOURCE").value("CFGEDIT") == ["9", "9", "9"]
    assert tracks["PART DRUMS"].value("MIDICOLORMAPFN")[0] == str(cmaps / "rockband_drums.png")
    assert tracks["PART GUITAR"].value("MIDICOLORMAPFN")[0].endswith("rockband_guitarbass.png")
    assert tracks["PART VOCALS"].value("MIDICOLORMAPFN")[0].endswith("rockband_vox-other.png")
    # lyrics use REAPER's meta header style
    xs = [n.header for n in tracks["PART VOCALS"].find("ITEM").find("SOURCE").nodes()]
    assert 'X 0 0 0 0 3 "PART VOCALS"' in xs and "X 960 0 0 0 5 do" in xs


def test_note_name_maps(tmp_path):
    maps = tmp_path / "maps"
    maps.mkdir()
    (maps / "RBN2 Pro Keys Expert.txt").write_text("// MIDI note name map generated by Reaper\n72\tHighest playable note B#3\n48\tLowest playable note C2\n")
    (maps / "RBN2 Vox.txt").write_text("36\tLowest Note C1\n")
    (maps / "RBN2 Vox_RSJ.txt").write_text("36\tH3 - Scream\n105\tPhrase Marker\n")
    (maps / "RBN2 Drums.txt").write_text("96\tEXPERT Kick\n")
    tpl = tmp_path / "t.RPP"
    tpl.write_text(OLD_SONG_TEMPLATE.replace('    MIDICOLORMAPFN', '    <MIDINOTENAMES\n      -1 1 old 0 1\n    >\n    MIDICOLORMAPFN'))
    chart = Chart(TempoMap.constant(120))
    chart.track("PART VOCALS").add_lyric(960, "la").add_note(960, 120, 60)
    wanted = ["PART REAL_KEYS_X", "PART VOCALS", "PART DRUMS", "BEAT", "EVENTS", "VENUE"]
    root = rproject.build(chart, {}, [], tpl, wanted=wanted, note_names=maps)
    tracks = {t.value("NAME")[0]: t for t in root.nodes("TRACK")}

    def names(t):
        node = tracks[t].find("MIDINOTENAMES")
        return [c.raw for c in node.children] if node else None
    assert names("PART REAL_KEYS_X") == ['-1 72 "Highest playable note B#3" 0 72', '-1 48 "Lowest playable note C2" 0 48']
    assert names("PART VOCALS")[-1] == '-1 36 "H3 - Scream" 0 36'        # the _RSJ map beats the stock one
    assert names("PART DRUMS") == ['-1 96 "EXPERT Kick" 0 96']           # template's old names replaced
    assert names("EVENTS") is None                                       # no map for it: left alone
    kids = [c.name for c in tracks["PART DRUMS"].nodes()]
    assert kids.index("MIDINOTENAMES") < kids.index("ITEM")


def test_review_markers_are_cleared_when_off(tmp_path):
    tpl = tmp_path / "t.RPP"
    tpl.write_text(TEMPLATE.replace('MARKER 1 3.5 "Mine" 0', 'MARKER 1 3.5 "Mine" 0\n  MARKER 2 9 "review: bass: old" 0'))
    root = rproject.build(Chart(TempoMap.constant(120)), {}, [], tpl)
    assert [ln.tokens[3] for ln in root.children if getattr(ln, "key", None) == "MARKER"] == ["Mine"]


def test_builtin_template_is_clean_and_names_the_mix_track(tmp_path):
    from yarginator.reaper import DEFAULT_TEMPLATE, bundled
    text = bundled(DEFAULT_TEMPLATE).read_text("utf-8", errors="replace")
    for leftover in ("Encanto", ".mp3", "GDrive", ":\\"):
        assert leftover not in text
    root = parse(text)
    assert all(not [c for c in it.find("SOURCE").children if getattr(c, "key", "") == "E" and c.tokens[2].startswith("9")]
               for t in root.nodes("TRACK") for it in t.nodes("ITEM"))          # no charted notes
    mix = tmp_path / "mix.wav"
    mix.write_bytes(b"")
    built = rproject.build(Chart(TempoMap.constant(120)), {"song": mix}, [], bundled(DEFAULT_TEMPLATE),
                           song_title="RedShedJed - Warm Up")
    assert next(built.nodes("TRACK")).value("NAME")[0] == "RedShedJed - Warm Up"


def test_preview_fx_on_keys_vocals_harmonies_none_on_five_lane():
    from yarginator.reaper import DEFAULT_TEMPLATE, bundled
    chart = Chart(TempoMap.constant(120))
    chart.track("PART VOCALS").add_lyric(960, "la").add_note(960, 120, 60).add_note(900, 400, 105)
    wanted = ["PART BASS", "PART GUITAR", "PART RHYTHM", "PART KEYS", "PART REAL_KEYS_X", "PART REAL_KEYS_E",
              "PART KEYS_ANIM_RH", "PART VOCALS", "HARM1", "HARM2", "HARM3", "BEAT", "EVENTS", "VENUE"]
    root = rproject.build(chart, {}, [], bundled(DEFAULT_TEMPLATE), wanted=wanted)
    tracks = {t.value("NAME")[0]: t for t in root.nodes("TRACK")}

    def chain(name):
        fx = tracks[name].find("FXCHAIN")
        if fx is None:
            return None, []
        filt = next((c for c in fx.nodes() if c.name == "JS"), None)
        return filt, [c.raw for c in fx.children if getattr(c, "key", "") == "BYPASS"]

    for name, (lo, hi) in (("PART REAL_KEYS_X", (48, 72)), ("PART REAL_KEYS_E", (48, 72)), ("PART KEYS", (96, 100)),
                           ("PART VOCALS", (36, 84)), ("HARM1", (36, 84)), ("HARM2", (36, 84)), ("HARM3", (36, 84))):
        filt, bypass = chain(name)
        assert filt is not None and "midi_note_filter" in filt.header, name
        assert filt.children[0].tokens[:3] == [str(lo), str(hi), "0"], name
        assert bypass and all(b == "BYPASS 1 0 0" for b in bypass), name       # there, but bypassed
        kids = [c.name for c in tracks[name].find("FXCHAIN").nodes()]
        assert kids.index("JS") < kids.index("VST"), name                    # filter before the synth
    # 5-lane guitar/rhythm/bass and marker tracks: no FX at all; the anim track keeps the template's synth
    for name in ("PART BASS", "PART GUITAR", "PART RHYTHM", "BEAT"):
        assert tracks[name].find("FXCHAIN") is None, name
    assert chain("PART KEYS_ANIM_RH")[0] is None
    # preview_on switches them on
    on = rproject.build(chart, {}, [], bundled(DEFAULT_TEMPLATE), wanted=wanted, preview_on=True)
    v = next(t for t in on.nodes("TRACK") if t.value("NAME")[0] == "HARM3")
    assert all(c.raw == "BYPASS 0 0 0" for c in v.find("FXCHAIN").children if getattr(c, "key", "") == "BYPASS")
    # FX ids are unique across the project
    ids = [c.raw for t in root.nodes("TRACK") for fx in t.nodes("FXCHAIN") for c in fx.children
           if getattr(c, "key", "") == "FXID"]
    assert len(ids) == len(set(ids))
    # a template without FX chains: nothing to add the filter to, and no crash
    assert rproject.build(chart, {}, [], None, wanted=wanted) is not None
    # applying again updates the filter instead of stacking a second one
    from yarginator.reaper import preview_fx
    v = next(t for t in parse(dumps(root)).nodes("TRACK") if t.value("NAME")[0] == "PART VOCALS")
    preview_fx.apply(v, "PART VOCALS")
    assert sum(1 for c in v.find("FXCHAIN").nodes() if c.name == "JS") == 1


def test_builtin_reaper_data_ships_with_the_package():
    from yarginator.reaper import DEFAULT_TEMPLATE, bundled, resolve
    from yarginator.reaper.note_names import MAP_FILES
    assert bundled(DEFAULT_TEMPLATE).is_file()
    assert {p.name for p in bundled("color_maps").glob("*.png")} >= {
        "rockband_drums.png", "rockband_guitarbass.png", "rockband_vox-other.png"}
    shipped = {p.name for p in bundled("note_names").glob("*.txt")}
    for _, files in MAP_FILES:
        assert any(f in shipped for f in files), files   # every chart track has a map
    base = bundled()
    assert resolve(None, base, base) == base and resolve("none", base, base) is None


def test_tokenize_quotes():
    assert tokenize('NAME "my track" \'it"s\' `a\'b"c` 3') == ["NAME", "my track", 'it"s', "a'b\"c", "3"]


def test_template_roundtrip_is_lossless():
    assert dumps(parse(TEMPLATE)) == TEMPLATE


def test_build_on_template(tmp_path):
    tpl = tmp_path / "t.RPP"
    tpl.write_text(TEMPLATE)
    chart = Chart(TempoMap.click_tracked(140, 2.0))
    chart.track("PART DRUMS").add_note(1920, 60, 96)
    chart.track("PART VOCALS").add_lyric(1920, "hey").add_note(1920, 120, 60)
    root = rproject.build(chart, {}, [ReviewItem(4.25, "vocals", "check me")], tpl)

    tracks = list(root.nodes("TRACK"))
    assert [t.value("NAME")[0] for t in tracks] == ["PART DRUMS", "PART VOCALS"]
    # template track kept its FX and settings, got a fresh MIDI item
    drums = tracks[0]
    assert drums.find("FXCHAIN") is not None and drums.line("VOLPAN") is not None
    items = list(drums.nodes("ITEM"))
    assert len(items) == 1 and items[0].find("SOURCE").args == ["MIDI"]
    # lyric written as a base64 meta event
    assert any(n.name == "X" for n in tracks[1].find("ITEM").find("SOURCE").nodes())
    # tempo envelope: offset measure + locked tempo
    pts = [ln.tokens for ln in root.find("TEMPOENVEX").children if ln.key == "PT"]
    assert len(pts) == 2 and abs(float(pts[1][2]) - 140) < 1e-3  # MIDI tempo is whole microseconds
    # user's marker kept, review marker added with the next free index
    markers = [ln.tokens for ln in root.children if getattr(ln, "key", None) == "MARKER"]
    assert markers[0][3] == "Mine" and markers[1][1] == "2" and "check me" in markers[1][3]
    # re-parse what we wrote
    parse(dumps(root))
